package io.matrixservices.core.general.model;
// default package
// Generated Oct 25, 2018 3:02:48 PM by Hibernate Tools 5.3.6.Final

import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * Ciudad generated by hbm2java
 */
@Entity
public class Ciudad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4549412105357880690L;
	private UUID ciudadid;
	private Pais pais;
	private String nombre;
	private String comentario;
	private short activo;

	public Ciudad() {
	}

	public Ciudad(UUID ciudadid, Pais pais, String nombre, short activo) {
		this.ciudadid = ciudadid;
		this.pais = pais;
		this.nombre = nombre;
		this.activo = activo;
	}

	public Ciudad(UUID ciudadid, Pais pais, String nombre, String comentario, short activo) {
		this.ciudadid = ciudadid;
		this.pais = pais;
		this.nombre = nombre;
		this.comentario = comentario;
		this.activo = activo;
	}

	@Id
	@Column(name = "ciudadid", nullable = false)
	public UUID getCiudadid() {
		return this.ciudadid;
	}

	public void setCiudadid(UUID ciudadid) {
		this.ciudadid = ciudadid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "paisid", nullable = false)
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

}
