package io.matrixservices.core.general.model;
// default package
// Generated Oct 25, 2018 3:02:48 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import javax.persistence.OneToMany;

/**
 * Persona generated by hbm2java
 */
@Entity
public class Persona implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2325658006123188258L;
	private UUID personaid;
	private String cedula;
	private String nombres;
	private String apellidos;
	private Short sexo;
	private Date fechaNac;
	private short activo;
	//private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public Persona() {
	}

	public Persona(UUID personaid, String cedula, String nombres,
			String apellidos, short activo) {
		this.personaid = personaid;
		this.cedula = cedula;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.activo = activo;
	}

	public Persona(UUID personaid,  String cedula, String nombres,
			String apellidos, Short sexo, Date fechaNac, short activo, Set<Usuario> usuarios /* Set<Cliente> clientes */ ) {
		this.personaid = personaid;
		this.cedula = cedula;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.sexo = sexo;
		this.fechaNac = fechaNac;
		this.activo = activo;
		//this.clientes = clientes;
	}

	@Id
	@Column(name = "personaid", nullable = false)
	public UUID getPersonaid() {
		return this.personaid;
	}

	public void setPersonaid(UUID personaid) {
		this.personaid = personaid;
	}

	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}


	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Short getSexo() {
		return this.sexo;
	}

	public void setSexo(Short sexo) {
		this.sexo = sexo;
	}

	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

/*	@OneToMany(mappedBy = "persona")
	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}*/

	

}
