package io.matrixservices.core.general.model;
// default package
// Generated Oct 25, 2018 3:02:48 PM by Hibernate Tools 5.3.6.Final

import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * UsuarioRol generated by hbm2java
 */
@Entity
public class UsuarioRol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5087968480695768384L;
	private UUID usuariorolid;
	private Rol rol;
	private Usuario usuario;
	private String login;
	private short activo;

	public UsuarioRol() {
	}

	public UsuarioRol(UUID usuariorolid, Rol rol, Usuario usuario, String login, short activo) {
		this.usuariorolid = usuariorolid;
		this.rol = rol;
		this.usuario = usuario;
		this.login = login;
		this.activo = activo;
	}

	@Id
	@Column(name = "usuariorolid", nullable = false)
	public UUID getUsuariorolid() {
		return this.usuariorolid;
	}

	public void setUsuariorolid(UUID usuariorolid) {
		this.usuariorolid = usuariorolid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rolid", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioid", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

}
