package io.matrixservices.core.exchange.model;
// default package
// Generated Oct 25, 2018 3:02:48 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import io.matrixservices.core.general.model.Persona;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente")
public class Cliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4144626902294114090L;
	private UUID clienteid;
	private Persona persona;
	private String codigoCliente;
	private Date clienteDesde;
	private String comentario;
	private short activo;
	private Set<CuentaCliente> cuentaClientes = new HashSet<CuentaCliente>(0);

	public Cliente() {
	}

	public Cliente(UUID clienteid, Persona persona, String codigoCliente, Date clienteDesde, String comentario,
			short activo) {
		this.clienteid = clienteid;
		this.persona = persona;
		this.codigoCliente = codigoCliente;
		this.clienteDesde = clienteDesde;
		this.comentario = comentario;
		this.activo = activo;
	}

	public Cliente(UUID clienteid, Persona persona, String codigoCliente, Date clienteDesde, String comentario,
			short activo, Set<CuentaCliente> cuentaClientes) {
		this.clienteid = clienteid;
		this.persona = persona;
		this.codigoCliente = codigoCliente;
		this.clienteDesde = clienteDesde;
		this.comentario = comentario;
		this.activo = activo;
		this.cuentaClientes = cuentaClientes;
	}

	@Id
	@Column(name = "clienteid", nullable = false)
	public UUID getClienteid() {
		return this.clienteid;
	}

	public void setClienteid(UUID clienteid) {
		this.clienteid = clienteid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "personaid", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "codigo_cliente", nullable = false, length = 500)
	public String getCodigoCliente() {
		return this.codigoCliente;
	}

	public void setCodigoCliente(String codigoCliente) {
		this.codigoCliente = codigoCliente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "cliente_desde", nullable = false, length = 13)
	public Date getClienteDesde() {
		return this.clienteDesde;
	}

	public void setClienteDesde(Date clienteDesde) {
		this.clienteDesde = clienteDesde;
	}

	@Column(name = "comentario", nullable = false, length = 500)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "activo", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@OneToMany(mappedBy = "cliente")
	public Set<CuentaCliente> getCuentaClientes() {
		return this.cuentaClientes;
	}

	public void setCuentaClientes(Set<CuentaCliente> cuentaClientes) {
		this.cuentaClientes = cuentaClientes;
	}

}
