package io.matrixservices.core.exchange.model;
// default package
// Generated Oct 25, 2018 3:02:48 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import io.matrixservices.core.general.model.Usuario;

/**
 * Monedacambio generated by hbm2java
 */
@Entity
@Table(name = "monedacambio")
public class Monedacambio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3613524558309345546L;
	private UUID monedacambioid;
	private Usuario usuario;
	private String nombre;
	private String abrevia;
	private Date fechacambio;
	private double cambioanterior;
	private double cambioactual;
	private short activo;

	public Monedacambio() {
	}

	public Monedacambio(UUID monedacambioid, Usuario usuario, String abrevia, Date fechacambio,
			double cambioanterior, double cambioactual, short activo) {
		this.monedacambioid = monedacambioid;
		this.usuario = usuario;
		this.abrevia = abrevia;
		this.fechacambio = fechacambio;
		this.cambioanterior = cambioanterior;
		this.cambioactual = cambioactual;
		this.activo = activo;
	}

	public Monedacambio(UUID monedacambioid, Usuario usuario, String nombre, String abrevia, Date fechacambio,
			double cambioanterior, double cambioactual, short activo) {
		this.monedacambioid = monedacambioid;
		this.usuario = usuario;
		this.nombre = nombre;
		this.abrevia = abrevia;
		this.fechacambio = fechacambio;
		this.cambioanterior = cambioanterior;
		this.cambioactual = cambioactual;
		this.activo = activo;
	}

	
	@Id
	@Column(name = "monedacambioid", nullable = false)
	public UUID getMonedacambioid() {
		return this.monedacambioid;
	}

	public void setMonedacambioid(UUID monedacambioid) {
		this.monedacambioid = monedacambioid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioid", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abrevia", nullable = false, length = 30)
	public String getAbrevia() {
		return this.abrevia;
	}

	public void setAbrevia(String abrevia) {
		this.abrevia = abrevia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechacambio", nullable = false, length = 13)
	public Date getFechacambio() {
		return this.fechacambio;
	}

	public void setFechacambio(Date fechacambio) {
		this.fechacambio = fechacambio;
	}

	@Column(name = "cambioanterior", nullable = false, precision = 17, scale = 17)
	public double getCambioanterior() {
		return this.cambioanterior;
	}

	public void setCambioanterior(double cambioanterior) {
		this.cambioanterior = cambioanterior;
	}
	
	@Column(name = "cambioactual", nullable = false, precision = 17, scale = 17)
	public double getCambioactual() {
		return this.cambioactual;
	}

	public void setCambioactual(double cambioactual) {
		this.cambioactual = cambioactual;
	}

	@Column(name = "activo", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

}
