package io.matrixservices.core.exchange.model;
// default package
// Generated Oct 25, 2018 3:02:48 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import io.matrixservices.core.general.model.Usuario;

/**
 * Moneda generated by hbm2java
 */
@Entity
@Table(name = "moneda")
public class Moneda implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7655079800307899138L;
	private UUID monedaid;
	private Usuario usuarioByUsuarioact;
	private Usuario usuarioByUsuariocambio;
	private Usuario usuarioByUsuarioins;
	private String nombre;
	private String abrevia;
	private Date fechains;
	private Date fechaact;
	private double cambioactual;
	private Date fechacambio;
	private short activo;

	public Moneda() {
	}

	public Moneda(UUID monedaid, Usuario usuarioByUsuarioact, Usuario usuarioByUsuariocambio,
			Usuario usuarioByUsuarioins, String abrevia, Date fechains, Date fechaact, double cambioactual,
			Date fechacambio, short activo) {
		this.monedaid = monedaid;
		this.usuarioByUsuarioact = usuarioByUsuarioact;
		this.usuarioByUsuariocambio = usuarioByUsuariocambio;
		this.usuarioByUsuarioins = usuarioByUsuarioins;
		this.abrevia = abrevia;
		this.fechains = fechains;
		this.fechaact = fechaact;
		this.cambioactual = cambioactual;
		this.fechacambio = fechacambio;
		this.activo = activo;
	}

	public Moneda(UUID monedaid, Usuario usuarioByUsuarioact, Usuario usuarioByUsuariocambio,
			Usuario usuarioByUsuarioins, String nombre, String abrevia, Date fechains, Date fechaact,
			double cambioactual, Date fechacambio, short activo) {
		this.monedaid = monedaid;
		this.usuarioByUsuarioact = usuarioByUsuarioact;
		this.usuarioByUsuariocambio = usuarioByUsuariocambio;
		this.usuarioByUsuarioins = usuarioByUsuarioins;
		this.nombre = nombre;
		this.abrevia = abrevia;
		this.fechains = fechains;
		this.fechaact = fechaact;
		this.cambioactual = cambioactual;
		this.fechacambio = fechacambio;
		this.activo = activo;
	}

	@Id
	@Column(name = "monedaid", nullable = false)
	public UUID getMonedaid() {
		return this.monedaid;
	}

	public void setMonedaid(UUID monedaid) {
		this.monedaid = monedaid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioact", nullable = false)
	public Usuario getUsuarioByUsuarioact() {
		return this.usuarioByUsuarioact;
	}

	public void setUsuarioByUsuarioact(Usuario usuarioByUsuarioact) {
		this.usuarioByUsuarioact = usuarioByUsuarioact;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuariocambio", nullable = false)
	public Usuario getUsuarioByUsuariocambio() {
		return this.usuarioByUsuariocambio;
	}

	public void setUsuarioByUsuariocambio(Usuario usuarioByUsuariocambio) {
		this.usuarioByUsuariocambio = usuarioByUsuariocambio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioins", nullable = false)
	public Usuario getUsuarioByUsuarioins() {
		return this.usuarioByUsuarioins;
	}

	public void setUsuarioByUsuarioins(Usuario usuarioByUsuarioins) {
		this.usuarioByUsuarioins = usuarioByUsuarioins;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abrevia", nullable = false, length = 30)
	public String getAbrevia() {
		return this.abrevia;
	}

	public void setAbrevia(String abrevia) {
		this.abrevia = abrevia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechains", nullable = false, length = 13)
	public Date getFechains() {
		return this.fechains;
	}

	public void setFechains(Date fechains) {
		this.fechains = fechains;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaact", nullable = false, length = 13)
	public Date getFechaact() {
		return this.fechaact;
	}

	public void setFechaact(Date fechaact) {
		this.fechaact = fechaact;
	}

	@Column(name = "cambioactual", nullable = false, precision = 17, scale = 17)
	public double getCambioactual() {
		return this.cambioactual;
	}

	public void setCambioactual(double cambioactual) {
		this.cambioactual = cambioactual;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechacambio", nullable = false, length = 13)
	public Date getFechacambio() {
		return this.fechacambio;
	}

	public void setFechacambio(Date fechacambio) {
		this.fechacambio = fechacambio;
	}

	@Column(name = "activo", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

}
