package io.matrixservices.core.exchange.model;
// default package
// Generated Oct 25, 2018 3:02:48 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * TipoCuenta generated by hbm2java
 */
@Entity
public class TipoCuenta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5283778210127474475L;
	private UUID tipocuentaid;
	private String nombre;
	private String abrevia;
	private short activo;
	private Set<CuentaCliente> cuentaClientes = new HashSet<CuentaCliente>(0);

	public TipoCuenta() {
	}

	public TipoCuenta(UUID tipocuentaid, String abrevia, short activo) {
		this.tipocuentaid = tipocuentaid;
		this.abrevia = abrevia;
		this.activo = activo;
	}

	public TipoCuenta(UUID tipocuentaid, String nombre, String abrevia, short activo, Set<CuentaCliente> cuentaClientes) {
		this.tipocuentaid = tipocuentaid;
		this.nombre = nombre;
		this.abrevia = abrevia;
		this.activo = activo;
		this.cuentaClientes = cuentaClientes;
	}

	@Id
	@Column(name = "tipocuentaid", nullable = false)
	public UUID getTipocuentaid() {
		return this.tipocuentaid;
	}

	public void setTipocuentaid(UUID tipocuentaid) {
		this.tipocuentaid = tipocuentaid;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abrevia", nullable = false, length = 30)
	public String getAbrevia() {
		return this.abrevia;
	}

	public void setAbrevia(String abrevia) {
		this.abrevia = abrevia;
	}

	@Column(name = "activo", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@OneToMany(mappedBy = "tipoCuenta")
	public Set<CuentaCliente> getCuentaClientes() {
		return this.cuentaClientes;
	}

	public void setCuentaClientes(Set<CuentaCliente> cuentaClientes) {
		this.cuentaClientes = cuentaClientes;
	}

}
