package io.matrixservices.core.exchange.model;
// default package
// Generated Oct 25, 2018 3:02:48 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoSocio generated by hbm2java
 */
@Entity
@Table(name = "tipo_socio")
public class TipoSocio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7814170618326130487L;
	private UUID tiposocioid;
	private String nombre;
	private String abrevia;
	private short activo;
	private Set<Banco> bancos = new HashSet<Banco>(0);

	public TipoSocio() {
	}

	public TipoSocio(UUID tiposocioid, String abrevia, short activo) {
		this.tiposocioid = tiposocioid;
		this.abrevia = abrevia;
		this.activo = activo;
	}

	public TipoSocio(UUID tiposocioid, String nombre, String abrevia, short activo, Set<Banco> bancos) {
		this.tiposocioid = tiposocioid;
		this.nombre = nombre;
		this.abrevia = abrevia;
		this.activo = activo;
		this.bancos = bancos;
	}

	@Id
	@Column(name = "tiposocioid", nullable = false)
	public UUID getTiposocioid() {
		return this.tiposocioid;
	}

	public void setTiposocioid(UUID tiposocioid) {
		this.tiposocioid = tiposocioid;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abrevia", nullable = false, length = 30)
	public String getAbrevia() {
		return this.abrevia;
	}

	public void setAbrevia(String abrevia) {
		this.abrevia = abrevia;
	}
	
	@Column(name = "activo", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@OneToMany(mappedBy = "tipoSocio")
	public Set<Banco> getBancos() {
		return this.bancos;
	}

	public void setBancos(Set<Banco> bancos) {
		this.bancos = bancos;
	}

}
