package io.matrixservices.core.exchange.model;
// default package
// Generated Oct 25, 2018 3:02:48 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoTransaccion generated by hbm2java
 */
@Entity
@Table(name = "tipo_transaccion")
public class TipoTransaccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7644772073577759628L;
	private UUID tipotransaccionid;
	private String nombre;
	private String abrevia;
	private short activo;
	private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);

	public TipoTransaccion() {
	}

	public TipoTransaccion(UUID tipotransaccionid, String abrevia, short activo) {
		this.tipotransaccionid = tipotransaccionid;
		this.abrevia = abrevia;
		this.activo = activo;
	}

	public TipoTransaccion(UUID tipotransaccionid, String nombre, String abrevia, short activo,
			Set<Transaccion> transaccions) {
		this.tipotransaccionid = tipotransaccionid;
		this.nombre = nombre;
		this.abrevia = abrevia;
		this.activo = activo;
		this.transaccions = transaccions;
	}

	@Id
	@Column(name = "tipotransaccionid", nullable = false)
	public UUID getTipotransaccionid() {
		return this.tipotransaccionid;
	}

	public void setTipotransaccionid(UUID tipotransaccionid) {
		this.tipotransaccionid = tipotransaccionid;
	}
	
	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@Column(name = "abrevia", nullable = false, length = 30)
	public String getAbrevia() {
		return this.abrevia;
	}

	public void setAbrevia(String abrevia) {
		this.abrevia = abrevia;
	}
	
	@Column(name = "activo", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@OneToMany(mappedBy = "tipoTransaccion")
	public Set<Transaccion> getTransaccions() {
		return this.transaccions;
	}

	public void setTransaccions(Set<Transaccion> transaccions) {
		this.transaccions = transaccions;
	}

}
