package io.matrixservices.core.exchange.model;
// default package
// Generated Oct 25, 2018 9:10:24 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import io.matrixservices.core.general.model.Usuario;

/**
 * Transferencia generated by hbm2java
 */
@Entity
@Table(name = "transferencia")
public class Transferencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9177078883660523247L;
	private UUID transferenciaid;
	private CuentaCliente cuentaCliente;
	private Transaccion transaccion;
	private Usuario usuarioByAutorizacionid;
	private Usuario usuarioByUsuarioid;
	private double monto;
	private Date fechatrans;
	private UUID verificada;
	private String numeroconfirmacion;
	private short activo;

	public Transferencia() {
	}

	public Transferencia(UUID transferenciaid, CuentaCliente cuentaCliente, Transaccion transaccion,
			Usuario usuarioByAutorizacionid, Usuario usuarioByUsuarioid, double monto, Date fechatrans,
			UUID verificada, String numeroconfirmacion, short activo) {
		this.transferenciaid = transferenciaid;
		this.cuentaCliente = cuentaCliente;
		this.transaccion = transaccion;
		this.usuarioByAutorizacionid = usuarioByAutorizacionid;
		this.usuarioByUsuarioid = usuarioByUsuarioid;
		this.monto = monto;
		this.fechatrans = fechatrans;
		this.verificada = verificada;
		this.numeroconfirmacion = numeroconfirmacion;
		this.activo = activo;
	}

	@Id
	@Column(name = "transferenciaid", nullable = false)
	public UUID getTransferenciaid() {
		return this.transferenciaid;
	}

	public void setTransferenciaid(UUID transferenciaid) {
		this.transferenciaid = transferenciaid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cuentaclienteid", nullable = false)
	public CuentaCliente getCuentaCliente() {
		return this.cuentaCliente;
	}

	public void setCuentaCliente(CuentaCliente cuentaCliente) {
		this.cuentaCliente = cuentaCliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transaccionid", nullable = false)
	public Transaccion getTransaccion() {
		return this.transaccion;
	}

	public void setTransaccion(Transaccion transaccion) {
		this.transaccion = transaccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "autorizacionid", nullable = false)
	public Usuario getUsuarioByAutorizacionid() {
		return this.usuarioByAutorizacionid;
	}

	public void setUsuarioByAutorizacionid(Usuario usuarioByAutorizacionid) {
		this.usuarioByAutorizacionid = usuarioByAutorizacionid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarioid", nullable = false)
	public Usuario getUsuarioByUsuarioid() {
		return this.usuarioByUsuarioid;
	}

	public void setUsuarioByUsuarioid(Usuario usuarioByUsuarioid) {
		this.usuarioByUsuarioid = usuarioByUsuarioid;
	}

	@Column(name = "monto", nullable = false, precision = 17, scale = 17)
	public double getMonto() {
		return this.monto;
	}

	public void setMonto(double monto) {
		this.monto = monto;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "fechatrans", nullable = false, length = 13)
	public Date getFechatrans() {
		return this.fechatrans;
	}

	public void setFechatrans(Date fechatrans) {
		this.fechatrans = fechatrans;
	}

	@Column(name = "verificada", nullable = false)
	public UUID getVerificada() {
		return this.verificada;
	}

	public void setVerificada(UUID verificada) {
		this.verificada = verificada;
	}

	@Column(name = "numeroconfirmacion", nullable = false, length = 30)
	public String getNumeroconfirmacion() {
		return this.numeroconfirmacion;
	}

	public void setNumeroconfirmacion(String numeroconfirmacion) {
		this.numeroconfirmacion = numeroconfirmacion;
	}

	@Column(name = "activo", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

}
