package io.matrixservices.core.exchange.model;
// default package
// Generated Oct 25, 2018 3:02:48 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaccion generated by hbm2java
 */
@Entity
@Table(name = "transaccion")
public class Transaccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5146905819464305646L;
	private UUID transaccionid;
	private CuentaCliente cuentaCliente;
	private TipoTransaccion tipoTransaccion;
	private double monto;
	private Date fechatransa;
	private UUID verificadatransf;
	private UUID verificadatransa;
	private short activo;
	private Set<Transferencia> transferencias = new HashSet<Transferencia>(0);

	public Transaccion() {
	}

	public Transaccion(UUID transaccionid, CuentaCliente cuentaCliente, TipoTransaccion tipoTransaccion,
			double monto, Date fechatransa, UUID verificadatransf, UUID verificadatransa,
			short activo) {
		this.transaccionid = transaccionid;
		this.cuentaCliente = cuentaCliente;
		this.tipoTransaccion = tipoTransaccion;
		this.monto = monto;
		this.fechatransa = fechatransa;
		this.verificadatransf = verificadatransf;
		this.verificadatransa = verificadatransa;
		this.activo = activo;
	}

	public Transaccion(UUID transaccionid, CuentaCliente cuentaCliente, TipoTransaccion tipoTransaccion,
			double monto, Date fechatransa, UUID verificadatransf, UUID verificadatransa, short activo,
			Set<Transferencia> transferencias) {
		this.transaccionid = transaccionid;
		this.cuentaCliente = cuentaCliente;
		this.tipoTransaccion = tipoTransaccion;
		this.monto = monto;
		this.fechatransa = fechatransa;
		this.verificadatransf = verificadatransf;
		this.verificadatransa = verificadatransa;
		this.activo = activo;
		this.transferencias = transferencias;
	}

	@Id
	@Column(name = "transaccionid", nullable = false)
	public UUID getTransaccionid() {
		return this.transaccionid;
	}

	public void setTransaccionid(UUID transaccionid) {
		this.transaccionid = transaccionid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clienteid", nullable = false)
	public CuentaCliente getCuentaCliente() {
		return this.cuentaCliente;
	}

	public void setCuentaCliente(CuentaCliente cuentaCliente) {
		this.cuentaCliente = cuentaCliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipotransaccionid", nullable = false)
	public TipoTransaccion getTipoTransaccion() {
		return this.tipoTransaccion;
	}

	public void setTipoTransaccion(TipoTransaccion tipoTransaccion) {
		this.tipoTransaccion = tipoTransaccion;
	}

	@Column(name = "monto", nullable = false, precision = 17, scale = 17)
	public double getMonto() {
		return this.monto;
	}

	public void setMonto(double monto) {
		this.monto = monto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechatransa", nullable = false, length = 13)
	public Date getFechatransa() {
		return this.fechatransa;
	}

	public void setFechatransa(Date fechatransa) {
		this.fechatransa = fechatransa;
	}

	@Column(name = "verificadatransf", nullable = false)
	public UUID getVerificadatransf() {
		return this.verificadatransf;
	}

	public void setVerificadatransf(UUID verificadatransf) {
		this.verificadatransf = verificadatransf;
	}

	@Column(name = "verificadatransa", nullable = false)
	public UUID getVerificadatransa() {
		return this.verificadatransa;
	}

	public void setVerificadatransa(UUID verificadatransa) {
		this.verificadatransa = verificadatransa;
	}
	
	@Column(name = "activo", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@OneToMany(mappedBy = "transaccion")
	public Set<Transferencia> getTransferencias() {
		return this.transferencias;
	}

	public void setTransferencias(Set<Transferencia> transferencias) {
		this.transferencias = transferencias;
	}

}
