package io.matrixservices.core.exchange.model;
// default package
// Generated Nov 24, 2018, 8:10:04 PM by Hibernate Tools 5.3.6.Final


import java.util.UUID;

import io.matrixservices.core.general.model.Usuario;

/**
 * UsuarioToken generated by hbm2java
 */
@SuppressWarnings("serial")
public class UsuarioToken implements java.io.Serializable {

	private UUID usuariotokenid;
	private Usuario usuario;
	private String tokenid;
	private String tokenlabel;
	private long duracion;
	private String ipaddress;
	private String permisos;
	private short activo;

	public UsuarioToken() {
	}

	public UsuarioToken(UUID usuariotokenid, Usuario usuario, String tokenid, String tokenlabel, long duracion,
			String ipaddress, String permisos, short activo) {
		this.usuariotokenid = usuariotokenid;
		this.usuario = usuario;
		this.tokenid = tokenid;
		this.tokenlabel = tokenlabel;
		this.duracion = duracion;
		this.ipaddress = ipaddress;
		this.permisos = permisos;
		this.activo = activo;
	}

	public UUID getUsuariotokenid() {
		return this.usuariotokenid;
	}

	public void setUsuariotokenid(UUID usuariotokenid) {
		this.usuariotokenid = usuariotokenid;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getTokenid() {
		return this.tokenid;
	}

	public void setTokenid(String tokenid) {
		this.tokenid = tokenid;
	}

	public String getTokenlabel() {
		return this.tokenlabel;
	}

	public void setTokenlabel(String tokenlabel) {
		this.tokenlabel = tokenlabel;
	}

	public long getDuracion() {
		return this.duracion;
	}

	public void setDuracion(long duracion) {
		this.duracion = duracion;
	}

	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	public String getPermisos() {
		return this.permisos;
	}

	public void setPermisos(String permisos) {
		this.permisos = permisos;
	}

	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

}
